image: node:8.17.0

options:
  docker: true
  size: 2x

clone:
  depth: full

definitions:
  services:
    docker:
      memory: 4096
  caches:
    cache: ~/.cache
  steps:
    - step: &sonar-quality-gate
        name: sonar quality gate
        size: 2x
        caches:
          - cache
          - docker
        script:
          - pipe: sonarsource/sonarcloud-scan:1.2.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.branch.name=$BITBUCKET_BRANCH'
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.4

pipelines:
  pull-requests:
    feat/*:
      - step: *sonar-quality-gate
    fix/*:
      - step: *sonar-quality-gate
  tags:
      dev-v*:
        - step:
            name: Build
            script:
              - npm install copyfiles@2.4.0 -g
              - yarn install
              - yarn build
            artifacts:
              - build/**
        - step:
            name: Deploy to S3
            deployment: DEV
            script:
              - pipe: atlassian/aws-s3-deploy:0.4.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: $BUCKET_NAME
                  ACL: 'public-read'
                  LOCAL_PATH: 'build'
  branches:
    master:
      - parallel:
          - step:
              name: Build and deploy
              deployment: UAT
              caches:
                - cache
                - docker
              trigger: manual
              script:
                - npm install copyfiles@2.4.0 -g
                - yarn install
                - yarn run build:uat
                - pipe: atlassian/ftp-deploy:0.3.5
                  variables:
                    USER: $FTP_USER
                    PASSWORD: $FTP_PASSWORD
                    SERVER: $FTP_HOST
                    REMOTE_PATH: $FTP_REMOTE_PATH
                    LOCAL_PATH: 'build'
              artifacts:
                - build/**
          - step: *sonar-quality-gate
