const content = `
<div>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">
   TERMS AND CONDITIONS FOR THE USE OF DIGITAL PLATFORM (&ldquo;TERMS AND CONDITIONS&rdquo;)
</span></strong></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">1.</span></strong><span style="width: 27.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">DEFINITION &amp; INTERPRETATION</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Definition</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.1.1.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">In this Terms and Conditions, the following words shall have the meaning hereby assigned to them except where the context otherwise require:-</span></p>
<table style="margin-left: 36pt; border: 0.75pt solid #000000; border-collapse: collapse;" cellspacing="0" cellpadding="0">
   <tbody>
      <tr>
         <td style="width: 98.1pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;"><span style="font-family: FSElliot-Pro;">User</span></p>
         </td>
         <td style="width: 306.4pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means a person:
               </span>
            </p>
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  (a)<span style="margin-left:7px">who has access via a web link to Principal’s website; and/ or</span>
               </span>
            </p> 
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  (b)<span style="margin-left:7px">such other person duly authorised by Principal from time to time;</span>
               </span>
            </p>
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  to access and/ or use the Digital Platform;
               </span>
            </p>                                      
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  Digital Platform
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means the website, portal, services, software and materials provided by Principal or made available via or through the  Digital Platform;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  Principal
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means Principal Asset Management Berhad (<span style="font-style: italic;">formerly known as CIMB-Principal Asset Management Berhad</span>), its affiliates, subsidiaries and/ or brand including any successors-in title  and assigns;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">Material</span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means all information, data or content provided or made available by Principal via or through the Digital Platform;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">Password</span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means any verification code, passwords, security information and procedures supplied to you by Principal to your access to the Digital Platform;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  Service
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means the specific tools, facilities, software and such other conveniences by whatever name so called and provided to or made available by Principal to the User;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  Software
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means such software made available by Principal;
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  Terms and Conditions
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; border-bottom-style: solid; border-bottom-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means all terms and conditions contained herein including any amendments, modifications and/ or variations from time to time; and
               </span>
            </p>
         </td>
      </tr>
      <tr>
         <td style="width: 98.1pt; border-top-style: solid; border-top-width: 0.75pt; border-right-style: solid; border-right-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  User ID
               </span>
            </p>
         </td>
         <td style="width: 306.4pt; border-top-style: solid; border-top-width: 0.75pt; border-left-style: solid; border-left-width: 0.75pt; padding-right: 5.03pt; padding-left: 5.03pt; vertical-align: top;">
            <p style="margin-top: 0pt; margin-bottom: 0pt; text-align: justify; font-size: 10px;">
               <span style="font-family: FSElliot-Pro;">
                  means your user identification information;
               </span>
            </p>
         </td>
      </tr>
   </tbody>
</table>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">&nbsp;</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.</span><span style="width: 25.07pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">In this Agreement, unless the context otherwise specifies:-</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.1.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">the term </span><span style="font-family: FSElliot-Pro;">"we", "us" and &lsquo;&lsquo;our&rsquo;&rsquo; are a reference to Principal;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.2.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">the term 'you' and 'your' are a reference to the User;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.3.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">words denoting the singular number shall include the plural and vice versa;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.4.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">words denoting the masculine gender include the feminine gender and neuter genders and vice versa;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.5.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Any reference in this Agreement to &ldquo;writing&rdquo; or related expression includes a reference to, e-mail or comparable means of communication;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.6.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Any reference in this Agreement to any provision of a statute, rules or regulation shall be construed as a reference to that provision as amended, re-enacted or extended at the relevant time; and</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">1.2.7.</span><span style="width: 19.72pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">The headings and sub-headings in this Agreement are for convenience only and shall not affect its interpretation of this Agreement.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">2.</span></strong><span style="width: 26.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">ACCEPTANCE</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">You accept and agree that your access to and the use of the Digital Platform shall at all times be governed by the Terms and Conditions stipulated herein and any operating rules and guidelines in relation to the Digital Platform as may be provided by Principal from time to time.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">3.</span></strong><span style="width: 27.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">PASSWORD</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">3.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You are authorised to access and use the Digital Platform through the entry of your User ID and the Password</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">3.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You agree that you will be solely responsible for all access to, use of and activity within the Digital Platform where it is effected through the use of your User ID and Password, including but not limited to any information submitted, messages posted, statements made and communications transmitted.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">3.3.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You hereby acknowledge your intention to be bound by all communications transmitted within or via the Digital Platform where it is initiated through the use of your User ID and your Password.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">3.4.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You shall be responsible for the security of your User ID and Password which includes your obligation to keep confidential and not reveal your User ID, Password or any other information relevant thereto to another party that can enable, assist or facilitate unauthorised access and use of the Digital Platform.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">3.5.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">If you believe that your User ID and Password have been compromised, you are required to notify the Principal immediately.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">4.</span></strong><span style="width: 27.49pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">AMENDMENTS</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">4.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal reserves its sole and absolute discretion the right to amend, vary or modify these Terms and Conditions from time to time. The continued use of the Digital Platform by you following such amendment, variation or modification shall be construe as the acceptance and agreement of such amendment, variation or modification.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">4.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">If you do not wish to be bound by any subsequent amendments, variations or modifications to these Terms and Conditions, you must cease to use the Digital Platform immediately.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">5.</span></strong><span style="width: 27.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">SERVICES</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">5.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Your ability to gain access to and use the Services will be based on your entitlement level as determined by Principal at its sole discretion from time to time.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">5.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">The Services made available and/or your entitlement level may be varied from time to time at Principal's sole discretion.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">5.3.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">While your access and use of the Digital Platform is provided free of charge, Principal reserves its sole and absolute discretion to levy a charge in relation to any of the Services or Materials provided or made available therein.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">6.</span></strong><span style="width: 27.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">PERMITTED USE</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Your use of the Digital Platform shall at all times be in compliance with the Terms and Conditions herein and with such other guidelines or directions as may be issued by Principal from time to time.</span></p>
<p style="margin-top: 0pt; margin-left: 31.5pt; margin-bottom: 10pt; text-indent: -31.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.</span><span style="width: 25.57pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">In the course of your access to and use of the Digital Platform, you are hereby prohibited from: -</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.1.</span><span style="width: 19.23pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">posting, disseminating, uploading or otherwise transmitting any messages, data or communications that are (i) offensive, defamatory, vulgar, abusive, threatening, harassing or libellous; (ii) which contains blatant bigotry racism, hatred, pornography or other objectionable content; which infringe the intellectual property rights of a third party; (ii) which contain viruses, trojan horses, worms or any other harmful or destructive or disruptive materials, files or programs; or (iv) may be considered as fake news under the relevant legislation; or (v)</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">which otherwise may give rise to criminal or civil liability or violate any applicable laws or regulations;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.2.</span><span style="width: 19.23pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">transmitting spam messages, chain or any type of unsolicited messages or communications to anyone who has not given their prior consent to receive such messages or communications;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.3.</span><span style="width: 19.23pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">posting on the Digital Platform any links to other internet sites without the prior consent of Principal;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.4.</span><span style="width: 19.23pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">disrupting the use of or interfering with the ability of others to effectively use the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform; and</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.2.5.</span><span style="width: 19.23pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">engaging in activities, whether lawful or unlawful, which Principal may determine as harmful to the users of the  Digital Platform, and which may be damaging to Principal's reputation and goodwill.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.3.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal reserves its sole and absolute discretion to determine the limit as to the frequency, volume and size of the messages, data and/or communications that you may transmit, receive, store, or post via or on the Digital Platform from time to time.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.4.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal is not obliged to monitor your use of the Digital Platform. However, we reserve the right to conduct random checks from time to time to ensure compliance with Principal’s Terms and Conditions and with such other guidelines or directions as may be issued by Principal or the relevant regulatory authorities from time to time.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">6.5.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Without prejudice to our right to limit, suspend or terminate your access and use of the Digital Platform herein, we reserve our sole and absolute discretion the right to block, filter, edit, delete or remove any messages, data or communications posted, disseminated, uploaded or otherwise transmitted by you which appears to violate our terms, policies or guidelines.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">7.</span></strong><span style="width: 27.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">REQUIREMENT</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">7.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal may stipulate the minimum hardware and/ or software requirement which will enable you to access the Digital Platform, the acquisition and use of which shall be at your own risk and expense.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">7.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Notwithstanding the above, Principal reserves its sole and absolute discretion and from time to time to change or update the minimum hardware and/ or software requirement in such instances as Principal deems fit including but not limited to where Principal makes any modification and/or improvement to the Digital Platform or where newer models of hardware or different versions of the software become available.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">7.3.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Your failure to change or upgrade the hardware and software in accordance with the requirement of Principal, may result in your inability to access and/ or obtain all features and/or Services of the  Digital Platform available to you and such features that corresponds to your entitlement level as a User.</span></p>
<p style="margin-top: 0pt; margin-left: 18pt; margin-bottom: 10pt; text-indent: -18pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">8.</span></strong><span style="width: 9.49pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="width: 18pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">SOFTWARE</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Further to the requirements (as stated in Clause 7) as may be stipulated by Principal for your access to and use of the Digital Platform, you may also be required to install certain Software which is proprietary to Principal on your computer by using the mode of installation as may be provided or made available to you by Principal.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">In the event that such Software is required, Principal hereby make available and grants you, for your own use, a non-exclusive, non-transferable, without a right to sub-license and revocable licence to use the Software for the purposes contemplated and authorised herein.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.3.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Your use of the Software is restricted to your use of the same in connection with the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform and in accordance with these Terms and Conditions.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.4.</span><span style="width: 25.07pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You are not permitted and shall not permit any other person to:</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.4.1.</span><span style="width: 12.22pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">copy, alter, modify, reverse engineer, decompile, reverse input or disassemble or reproduce the software;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.4.2.</span><span style="width: 12.22pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">publish or disclose the Software or any information or data in relation thereto; or</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.4.3.</span><span style="width: 12.22pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">assign, transfer, sub-license or otherwise make any profit, monetary or otherwise out of the Software.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.5.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You shall notify Principal immediately if you become aware of any unauthorised use of the Software.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">8.6.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal reserves its sole and absolute discretion at any time without notice to you to terminate the said licence or take any action it reasonably believes as necessary to comply with any applicable law.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">9.</span></strong><span style="width: 26.49pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">COMPLIANCE</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">9.1.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You shall comply with all directions, instructions given and/or regulations issued by Principal to you in relation to the Digital Platform.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">9.2.</span><span style="width: 25.07pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Notwithstanding the above, nothing shall affect your right to exercise your own judgement and to utilise your skills as you consider most appropriate in order to achieve compliance with the said directions, instructions and regulations or otherwise to comply with the obligations under these Terms and Conditions.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">10.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">EXCLUSION </span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">The Digital Platform is provided ''AS IS'' and ''AS AVAILABLE'', without any warranties, conditions, guarantees or representation of any kind whether expressed or implied. To the fullest extent permissible pursuant to applicable laws, Principal disclaims all warranties, expressed or implied, in relation to the Digital Platform, including but not limited to, implied warranties of merchantability and fitness for a particular purpose, of title or non-infringement of third party rights or any other warranties or conditions arising by statute or otherwise in law or from course of dealing or use.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Without prejudice to the generality of the above and further thereto, Principal does not warrant or make any representations:</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.1.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">that the Digital Platform will meet your requirements or will be uninterrupted, timely, error-free, free from viruses, trojan horses, worms or any other harmful, destructive or disruptive components or that defects will be corrected;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.2.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">that there will be no delays, failures, errors or loss of Materials or of your messages, data or communications that are transmitted or posted via or on the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.3.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">as to the accuracy, reliability, adequacy, quality and completeness of the Digital Platform;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.4.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">as to the Materials, postings, posting responses or other communications found on the Digital Platform;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.5.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">that any advice or Materials, obtained by you from us through the Digital Platform is true, accurate or complete and you agree that you shall be responsible for making your own assessment of the contents prior to acting and/or relying on any such Materials; and</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.2.6.</span><span style="width: 19.65pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">that the Digital Platform is appropriate or available for use in any location other than Malaysia. Those who choose to access and use the Digital Platform are responsible for compliance with all applicable local laws in their jurisdiction.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.3.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You are responsible for ensuring that your access to and use of the Digital Platform is not illegal or prohibited by any applicable laws. You must take your own precautions to ensure that the process which you employ for accessing the Digital Platform does not expose you to the risk of viruses, malicious computer code or other forms of interference which may cause damage to you and/or the computer equipment used by you to access and use the Digital Platform.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.4.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You acknowledge and agree that such Materials as you may download or obtain through the use of the Digital Platform is downloaded or obtained at your own discretion and risk and that Principal accepts no responsibility for any damage to your computer system or loss of data which may result from the downloading or use of such Materials.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.5.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">For the avoidance of doubt, Principal does not accept responsibility for any interference or damage to any computer equipment used by you which arises in connection with your use of the Digital Platform or any linked websites.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">10.6.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">The Services featured or referred to in this  Digital Platform are only for those persons registered as a Principal’s User.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">11.</span></strong><span style="width: 21.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">EXCLUSION OF LIABILITY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Under no circumstances, including, but not limited to negligence, will Principal or any party involved in creating, producing, or making available the Digital Platform be liable to you for any direct, incidental, indirect, consequential, special or punitive damages resulting from:</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.1.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">your access to and use of (whether authorised or otherwise), or the inability to access and use, the</span><span style="font-family: FSElliot-Pro;">Digital Platform; </span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.2.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">your reliance on the Materials provided by Principal or on or accessed through the Digital Platform;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.3.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">your failure to comply with the Terms and Conditions herein;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.4.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">unauthorised access to, destruction or alteration of your communications, data, information or transmissions via or on the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform or on your computer;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.5.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">any damage to or viruses that may infect your computer equipment or other property as a result of your access to, use of, or browsing of the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform or your downloading of and/or use of any Materials, including but not limited to information, data, text, images, video, or audio from the</span><span style="font-family: FSElliot-Pro;">&nbsp; </span><span style="font-family: FSElliot-Pro;">Digital Platform;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.6.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">the acts and omission of the User or any other third party;</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.7.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">the exercise by Principal of its rights and discretion pursuant herein; or</span></p>
<p style="margin-top: 0pt; margin-left: 76.5pt; margin-bottom: 10pt; text-indent: -40.5pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.1.8.</span><span style="width: 19.16pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">delay or failure of the  Digital Platform or breach or omission on the part of Principal which is due to circumstances beyond the reasonable control of Principal.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">11.2.</span><span style="width: 16.5pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">This exclusion shall take effect to the fullest extent permitted by law.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">12.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">COPYRIGHT</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">All Materials provided or made available through the Digital Platform (including but not limited to text, graphics, logos, icons, sound recordings and videos) whether by Principal or any other third party is protected by copyright, trademarks, patents and any other applicable intellectual property and proprietary laws and is owned and/or controlled by us and/or our third party content providers.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Unless otherwise permitted by Principal in writing, no Materials comprising the Digital Platform and/or made available via the Digital Platform may be modified, copied, adapted, stored, displayed, reproduced, republished, posted, transmitted, distributed and/or used in the creation of derivative works.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.3.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Where required, you may download one (1) copy of the Materials from the Digital Platform for your personal and non-commercial use only, subject to your leaving all copyright and other property notices intact unless you have been given express authorisation by Principal or the relevant third party content provider.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.4.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You agree that you do not acquire any ownership rights in any downloaded Materials and that all rights in the Digital Platform and in any Materials provided or made available therein.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.5.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You warrant that you have all the necessary rights and licenses to make available on the Digital Platform, any information, data or content that you transmit to and/or communicate through the Digital Platform. You further agree that Principal shall not be responsible for any loss or damages arising from your transmitting, communicating and/or making available the said information, data or content.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.6.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">By transmitting, communicating and/or making available the said information, data or content on or through the Digital Platform, you grant Principal and the other users of the Digital Platform the right or license to access, view and download such information, data or content for their use.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">12.7.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Further, you agree that Principal shall not be responsible for the use of the information, data or content you have so transmitted, communicated and/or made available on or through the Digital Platform by any other users of the Digital Platform.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">13.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">THIRD PARTY LINKS</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">Principal&rsquo;s Digital Platform may contain third party or external links to other websites that are not managed or controlled by Principal. These links are provided for convenience only and may not remain current or be maintained. Principal is not responsible for the content or privacy practices associated with such links. You acknowledge that any links on the Digital Platform shall not be construed by you as an endorsement, approval or recommendation by Principal of the owners or operators of the links, or of any information, graphics, materials, products or services referred to, contained on or received from those links, unless and to the extent stipulated to the contrary.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">14.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">GOVERNING LAW</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">These Terms and Conditions are governed by the laws in force in Malaysia. You agree to submit to the exclusive jurisdiction of the courts of Malaysia in relation to any dispute arising from this agreement.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">15.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">CONFIDENTIALLY &amp; PRIVACY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">15.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You hereby undertake that you shall not, without Principal’s express written consent, disclose any data, information or material pertaining to or in connection with Principal or its investors pursuant to these Terms and Conditions, to any third party other than the relevant authorised persons who have a right to such disclosure.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">15.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You agree that Principal has the right to make use of or otherwise make available such information pertaining to you and your use of the Digital Platform for the purpose of enforcing or defending any of our rights, to comply with all applicable legislation, laws and regulations as well as the requirements of any legal or regulatory bodies, to enhance the quality of the Services and to prevent fraud or illegal activities.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">15.3.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You further agree that Principal has the right to make available such information to our business associates, affiliates, advisors or relevant third parties in aggregate form from which your identity cannot be ascertained.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">16.</span></strong><span style="width: 21.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">SECURITY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">16.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Principal will endeavour to protect the information or data transmitted through or via the Digital Platform and to preserve the integrity of such data or transmission. However, Principal does not warrant and cannot ensure the security of any such data or information transmitted to and received by us.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">16.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">For the purposes of the security of the Digital Platform, you acknowledge that Principal reserves the right to monitor all your activities conducted via or through the Digital Platform, to the fullest extent permissible under applicable laws.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">17.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">TERMINATION </span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">17.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Your access to and use of the Digital Platform may be terminated at any time by Principal without assigning any reason whatsoever or giving you any notice.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">17.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You acknowledge that we have the right to suspend and/or terminate your User ID and Password without having to obtain your approval or justify such suspension and/or termination or give you prior notice of the same.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">17.3.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You shall not hold Principal liable or responsible for any loss or damage which you may suffer due to the suspension and/or termination of the same.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">17.4.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You shall, upon termination of your access to the Digital Platform, return all copies of the Materials and Software in your possession or delete, destroy or make them permanently unusable as may be instructed by Principal.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">17.5.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">In the event of termination, clauses 3, 9, 10, 11, 12, 14, 15, 16, 17, 20 and 23 shall survive termination and shall continue to have full force and effect.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">18.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">SEVERABILITY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">18.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You agree that if any provision of these Terms and Conditions is held to be invalid or unenforceable pursuant to any applicable law, the said provision shall be fully severed from these Terms and Conditions and these Terms and Conditions shall be construed as if the said invalid or unenforceable provision had not formed part of this Agreement.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">18.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Further, any such invalidity or unenforceability shall not affect or impair the remaining Terms and Conditions herein which shall continue to remain in full force and effect.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">19.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">WAIVER</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">You agree that any failure on the part of Principal, whether continuous or otherwise, in exercising its rights, power, privileges, remedies or provisions under these Terms and Conditions or any failure or delay in insisting on compliance with any of the provisions in these Terms and Conditions shall not constitute a waiver by Principal of any such rights, power, privileges, remedies or provisions in relation to these Terms and Conditions.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">20.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">INDEMNITY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">You hereby agree to indemnify and keep indemnified Principal, its servants, employees and/or its contractors from all liabilities, claims, losses, expenses or damages including any legal fees which may be incurred by Principal, arising directly or indirectly or in association with and as a result of your use or misuse of the Digital Platform, or your breach of these Terms and Conditions howsoever occasioned, or claims made by a third party against Principal in relation to your access to and use of the Digital Platform and/or the Services provided therein.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">21.</span></strong><span style="width: 21.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">INSTRUCTIONS</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">21.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">Where any of the Services allow you to issue instructions to Principal, Principal shall execute any instructions received from you or any other person or from any third party that uses your User ID and Password in order to gain access to the Digital Platform. Such instructions shall be deemed as being issued directly by you regardless of whether it was issued by an authorised third party or otherwise. Such instructions shall be binding upon you following transmission of the same.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">21.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You agree that Principal shall not be responsible or liable for any loss incurred by you or any other person or third party in the event that we have acted upon any instruction transmitted to us based upon the use of your User ID and Password.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">21.3.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">If you suspect or have reason to suspect that your instruction was not transmitted accurately or in its entirety, you shall inform us immediately. You further agree that we shall not be responsible or liable for any corruption, interruptions, omission, errors, delays, non-receipt or misrepresentation of your instruction howsoever caused.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">21.4.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">We reserve the right, at our sole discretion, to decline any instructions given by you, where such instructions are in contradiction with our policy or any rules or regulations currently in force or for any other reasons.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">22.</span></strong><span style="width: 21.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">AVAILABILITY</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">22.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">The Digital Platform and the Services provided herein will be made available subject to Principal’s sole and absolute discretion. Nevertheless, you acknowledge that there may be times when some or all of the Digital Platform may not be accessible owing to system maintenance or due to reasons beyond our control. You accept and acknowledge that we cannot guarantee that the Digital Platform will be available at all times.</span></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">22.2.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">If for any reason, the Digital Platform or parts thereof are not available, you hereby agree that you will use alternative means to communicate with Principal.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">23.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">EVIDENCE</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">You agree and acknowledge that in the absence of a manifest error, all evidence of information submitted, messages posted, statements made and/or communications transmitted, including any evidence in the form of, amongst others, computer printouts, transaction logs, and any other form of information and data storage, shall be binding upon you and treated as conclusive evidence of your communication for all purposes.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;"><strong><span style="font-family: FSElliot-Pro;">24.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">NOTICES</span></strong></p>
<p style="margin-top: 0pt; margin-left: 36pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">24.1.</span><span style="width: 20.5pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">You consent to all notices and other forms of communications which concern the  Digital Platform or as required by these Terms and Conditions, as may be given by Principal in the following manner:-</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">24.1.1.</span><span style="width: 14.15pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">by ordinary post to your last known address found in Principal's records, and such notification shall be deemed as received two (2) days after posting ;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">24.1.2.</span><span style="width: 14.15pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">by electronic mail to your last known e-mail address found in Principal's records, and such notification shall be deemed as received twenty four (24) hours after transmission of the same;</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">24.1.3.</span><span style="width: 14.15pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">by broadcasting a message on the Digital Platform; or</span></p>
<p style="margin-top: 0pt; margin-left: 72pt; margin-bottom: 10pt; text-indent: -36pt; text-align: justify; line-height: 115%; font-size: 10px;"><span style="font-family: FSElliot-Pro;">24.1.4.</span><span style="width: 14.15pt; text-indent: 0pt; display: inline-block;">&nbsp;</span><span style="font-family: FSElliot-Pro;">if notified to you in any other manner deemed fit by Principal.</span></p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;">
   <strong><span style="font-family: FSElliot-Pro;">25.</span></strong><span style="width: 20.91pt; display: inline-block;">&nbsp;</span><strong><span style="font-family: FSElliot-Pro;">CONTACT DETAILS</span></strong>
</p>
<p style="margin-top: 0pt; margin-bottom: 10pt; text-align: justify; line-height: 115%; font-size: 12px;">
   <span style="width: 32pt; display: inline-block;">&nbsp;</span>
   <span style="font-family: FSElliot-Pro;">For any enquiries, feedback and/ or complaints, you may reach us by:-</span>
</p>
<p style="">
   <table style="font-size: 12px;border:1px solid #000;margin-left:45px">
      <tr>
         <td style="padding:5px;align:top;border:1px solid #000;font-weight:bold;">
            <strong>No</strong>
         </td>
         <td style="padding:5px;border:1px solid #000;font-weight:bold;">
            <strong>Description</strong>
         </td>
         <td style="padding:5px;border:1px solid #000;font-weight:bold;">
            <strong>Particulars</strong>
         </td>                  
      </tr>
      <tr>
         <td style="padding:5px;align:top;border:1px solid #000">
            1
         </td>
         <td style="padding:5px;border:1px solid #000">
            Phone
         </td>
         <td style="padding:5px;border:1px solid #000">
            03-77237261
         </td>                  
      </tr>
      <tr>
         <td style="padding:5px;align:top;border:1px solid #000">
            2
         </td>
         <td style="padding:5px;border:1px solid #000">
            Email
         </td>
         <td style="padding:5px;border:1px solid #000">
            service@principal.com.my
         </td>                  
      </tr> 
      <tr>
         <td style="padding:5px;align:top;border:1px solid #000">
            3
         </td>
         <td style="padding:5px;border:1px solid #000">
            Post
         </td>
         <td style="padding:5px;border:1px solid #000">
            <div>
               50, 52 & 54, Jalan SS21/39 
            </div>
            <div>
               Damansara Utama
            </div>
            <div>
               47400 Petaling Jaya
            </div>    
            <div>
               Selangor
            </div>                    
         </td>                  
      </tr>                   
   </table>
</p>
<center>
<p style="padding:30px 0 0 0">
   I have read and understood, agree the <a href="https://www.principal.com.my/en/terms-of-use-my" style="color:rgb(0, 145, 218)" target="_blank">Terms of Use of Principal</a>
</p>
</center>
</div>
`;

export default content;
