/*
 *
 * Login constants
 *
 */

export const PROCESSING = 'app/Login/PROCESSING';
export const DEFAULT_ACTION = 'app/Login/DEFAULT_ACTION';
export const LOGIN = 'app/Login/LOGIN'; // check userID
export const LOGIN_SUCCESS = 'app/Login/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'app/Login/LOGIN_FAIL';

export const USERID_CHECK = 'app/Login/USERID_CHECK';
export const USERID_CHECK_SUCCESS = 'app/Login/USERID_CHECK_SUCCESS';
export const USERID_CHECK_FAIL = 'app/Login/USERID_CHECK_FAIL';

export const AGREEMENT_ACCEPT = 'app/Login/AGREEMENT_ACCEPT';
export const MODE_SET = 'app/Login/MODE_SET';

export const USERID_VERIFY = 'app/Login/USERID_VERIFY';
export const USERID_VERIFY_SUCCESS = 'app/Login/USERID_VERIFY_SUCCESS';
export const USERID_VERIFY_FAIL = 'app/Login/USERID_VERIFY_FAIL';

export const OTP_POST = 'app/Login/OTP_POST';
export const OTP_POST_SUCCESS = 'app/Login/OTP_POST_SUCCESS';
export const OTP_POST_FAIL = 'app/Login/OTP_POST_FAIL';

export const SECRETS_POST = 'app/Login/SECRETS_POST';
export const SECRETS_POST_SUCCESS = 'app/Login/SECRETS_POST_SUCCESS';
export const SECRETS_POST_FAIL = 'app/Login/SECRETS_POST_FAIL';

export const USERID_RECOVER = 'app/Login/USERID_RECOVER';
export const USERID_RECOVER_SUCCESS = 'app/Login/USER_ID_RECOVER_SUCCESS';
export const USERID_RECOVER_FAIL = 'app/Login/USERID_RECOVER_FAIL';

export const CHANGE_PASSWORD_SUCCESS = 'app/Login/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'app/Login/CHANGE_PASSWORD_FAIL';

export const CHANGE_PASSWORD_OTP_REQUEST = 'app/Login/CHANGE_PASSWORD_OTP_REQUEST';
export const CHANGE_PASSWORD_OTP_REQUEST_SUCCESS = 'app/Login/CHANGE_PASSWORD_OTP_REQUEST_SUCCESS';
export const CHANGE_PASSWORD_OTP_REQUEST_FAIL = 'app/Login/CHANGE_PASSWORD_OTP_REQUEST_FAIL';
export const EXEC_AFTER_CHANGE_PASSWORD_OTP_VERIFY_SUCCESS = 'app/Login/EXEC_AFTER_CHANGE_PASSWORD_OTP_VERIFY_SUCCESS';

export const INIT_RESET_PASSWORD = 'app/Login/INIT_RESET_PASSWORD';
export const INIT_RESET_PASSWORD_SUCCESS = 'app/Login/INIT_RESET_PASSWORD_SUCCESS';
export const INIT_RESET_PASSWORD_FAIL = 'app/INIT_RESET_PASSWORD_FAIL';
export const RESET_PASSWORD = 'app/Login/RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'app/Login/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'app/Login/RESET_PASSWORD_FAIL';
export const RESET_TOKEN_SAVE = 'app/Login/RESET_TOKEN_SAVE';

export const RESET_PASSWORD_TOKEN_VERIFY = 'app/Login/RESET_PASSWORD_TOKEN_VERIFY';
export const RESET_PASSWORD_TOKEN_VERIFY_SUCCESS = 'app/Login/RESET_PASSWORD_TOKEN_VERIFY_SUCCESS';
export const RESET_PASSWORD_TOKEN_VERIFY_FAIL = 'app/Login/RESET_PASSWORD_TOKEN_VERIFY_FAIL';

export const RESET_PASSWORD_EXECUTE = 'app/Login/RESET_PASSWORD_EXECUTE';
export const RESET_PASSWORD_EXECUTE_SUCCESS = 'app/Login/RESET_PASSWORD_EXECUTE_SUCCESS';

export const LOGOUT = 'app/Login/LOGOUT';
export const LOGOUT_SUCESS = 'app/Login/LOGOUT_SUCCESS';

export const ERROR_RESET = 'app/Login/ERROR_RESET';

export const CLOSE_OTP_MODAL = 'app/Login/CLOSE_OTP_MODAL';

export const SET_OTP_ERROR = 'app/Login/SET_OTP_ERROR';

export const SEND_OTP_SUCCESS_TOKEN = 'app/Login/SEND_OTP_SUCCESS_TOKEN';

export const SEND_OTP_FAIL_TOKEN = 'app/Login/SEND_OTP_FAIL_TOKEN';

export const INIT_FIRST_TIME_LOGIN_OTP = 'app/Login/INIT_FIRST_TIME_LOGIN_OTP';

export const INIT_FIRST_TIME_LOGIN_OTP_SUCCESS = 'app/Login/INIT_FIRST_TIME_LOGIN_OTP_SUCCESS';

export const INIT_FIRST_TIME_LOGIN_OTP_FAIL = 'app/Login/INIT_FIRST_TIME_LOGIN_OTP_FAIL';

export const OPEN_FIRST_TIME_LOGIN_OTP_MODAL = 'app/Login/OPEN_FIRST_TIME_LOGIN_OTP_MODAL';

export const SAVE_FIRST_TIME_LOGIN_TOKEN_FROM_OTP = 'app/Login/SAVE_FIRST_TIME_LOGIN_TOKEN_FROM_OTP';

export const EXEC_AFTER_OTP_FIRST_TIME_LOGIN_OTP_SUCCESS = 'app/Login/EXEC_AFTER_OTP_FIRST_TIME_LOGIN_OTP_SUCCESS';

export const EXEC_AFTER_OTP_FIRST_TIME_LOGIN_OTP_FAIL = 'app/Login/EXEC_AFTER_OTP_FIRST_TIME_LOGIN_OTP_FAIL';

export const SAVE_TOKEN_OF_FIRST_TIME_LOGIN_OTP_SUCCESS_FROM_EXEC_AFTER_OTP =
  'app/Login/SAVE_TOKEN_OF_FIRST_TIME_LOGIN_OTP_SUCCESS_FROM_EXEC_AFTER_OTP';

export const VERIFY_USERNAME_AND_PASSWORD = 'app/Login/VERIFY_USERNAME_AND_PASSWORD';
export const SET_USERNAME_AND_PASSWORD_VERIFY_STATUS = 'app/Login/SET_USERNAME_AND_PASSWORD_VERIFY_STATUS';

export const MARKET_NEWS_REQUEST = 'app/Login/MARKET_NEWS_REQUEST';
export const MARKET_NEWS_SUCCESS = 'app/Login/MARKET_NEWS_SUCCESS';
export const MARKET_NEWS_FAILED = 'app/Login/MARKET_NEWS_FAILED';

export const PASSWORD_REGEX = /^(?=.*?[A-Z])(?=.*?[0-9]).{8,}$/;

export const RESET = 'app/Login/RESET';
export const RESET_CHANGE_PASSWORD_STATE = 'app/Login/RESET_CHANGE_PASSWORD_STATE';
export const SET_CHANGE_PASSWORD_MODEL_OPEN = 'app/Login/SET_CHANGE_PASSWORD_MODEL_OPEN';
